[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "libras"
version = "0.1.0"
description = "Reconhecimento de palavras em Libras com MediaPipe + LSTM"
requires-python = ">=3.10"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]
